name: ci
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: wy1140174371/flask_web
          tags: v1, latest
          directory: demos/docker/flask_web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 微信提醒
      - name: send to bark
        run: |
            curl https://barkserver.wyatt.plus/xmfycovmqxjwvrra/ci/success
